### PR TITLE
Fix Graphite statistics collecting in driver

### LINKED ISSUE #20: Run measurements must be pulled from Graphite after delay to be complete
Currently benchto pulls env utilization measurements as soon as run execution ends. However, at least when using Graphite, the stats are not available in real-time and should be pulled after some time. Bonus would be to recognize when the stats are not fully available yet, but maybe that's not needed and a delay will be sufficient.

### PR DESCRIPTION
**Pull request by findepi**
Fixes #20

### CODE REVIEW

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java [hunk 1]
```diff
@@ -108,8 +108,18 @@ private URI buildLoadMetricsURI(Map<String, String> metrics, ZonedDateTime from,
...
-            dataPoints[i] = value == null ? 0 : value;
+            if (value == null) {
+                /*
+                 * Graphite returns null for an aggregation if *all* ingredients are null. We should query Graphite after
+                 * delay, so that all ingredients *are* present, so aggregation should not be null too.
+                 *
+                 * Note however, that non-null value for e.g. an average or sum does not mean that the value can be trusted.
+                 * Some data points can still be missing.
+                 */
+                LOGGER.error("null data point returned from Graphite");
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java]: maybe we should fail here instead?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java [hunk 2]
```diff
@@ -72,10 +73,10 @@ public void initQueryMetrics()
     }
 
     @Override
-    public List<Measurement> loadMeasurements(Measurable measurable)
+    public CompletableFuture<List<Measurement>> loadMeasurements(Measurable measurable)
     {
         if (!shouldLoadGraphiteMetrics(measurable)) {
-            return emptyList();
+            return CompletableFuture.completedFuture(emptyList());
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: static import

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java [hunk 3]
```diff
@@ -72,10 +73,10 @@ public void initQueryMetrics()
     }
 
     @Override
-    public List<Measurement> loadMeasurements(Measurable measurable)
+    public CompletableFuture<List<Measurement>> loadMeasurements(Measurable measurable)
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: what is the benefit of `Future` here?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java [hunk 4]
```diff
@@ -75,11 +78,19 @@ public void benchmarkStarted(Benchmark benchmark)
...
-                .addMeasurements(getMeasurements(benchmarkExecutionResult));
-
-        benchmarkServiceClient.finishBenchmark(benchmarkExecutionResult.getBenchmark().getUniqueName(), benchmarkExecutionResult.getBenchmark().getSequenceId(), requestBuilder.build());
+        getMeasurements(benchmarkExecutionResult)
+                .thenApply(measurements -> {
+                    return new FinishRequestBuilder()
+                            .withStatus(benchmarkExecutionResult.isSuccessful() ? ENDED : FAILED)
+                            .addMeasurements(measurements);
+                })
+                .thenApply(FinishRequestBuilder::build)
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java]: run `build ` in previous lambda

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/measurements/ThroughputMeasurementProvider.java [hunk 5]
```diff
@@ -29,12 +30,17 @@
...
         if (measurable instanceof BenchmarkExecutionResult && measurable.getBenchmark().isConcurrent() && measurable.isSuccessful()) {
-            return ImmutableList.of(measurement("throughput", "QUERY_PER_SECOND", calculateThroughput((BenchmarkExecutionResult) measurable)));
+            measurements = ImmutableList.of(measurement("throughput", "QUERY_PER_SECOND", calculateThroughput((BenchmarkExecutionResult) measurable)));
         }
-        return emptyList();
+        else {
+            measurements = emptyList();
+        }
+
+        return CompletableFuture.completedFuture(measurements);
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/measurements/ThroughputMeasurementProvider.java]: If I understand correctly, this code is still serial. What is the benefits of using `Future`-based API here?

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java [hunk 6]
```diff
@@ -126,7 +127,7 @@ public void startExecution(String uniqueName, String benchmarkSequenceId, String
     @Retryable(value = {TransientDataAccessException.class, DataIntegrityViolationException.class}, maxAttempts = 1)
```
Comment (kokosing) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: maxAttemtps = 1 ? hm....

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java [hunk 7]
```diff
@@ -40,9 +52,34 @@
 
     private static final double GRAPHITE_WAIT_BETWEEN_REPORTING_RESOLUTION_COUNT = 2;
 
+    private static final Duration SHUTDOWN_ASYNC_TASKS_WAIT_TIMEOUT = Duration.ofMinutes(20);
+    private static final int SHUTDOWN_ASYNC_TASKS_WAIT_REPORT_TIMES = 20;
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java]: does it make driver to wait 20 minutes after benchmark completion?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java [hunk 8]
```diff
@@ -40,9 +52,34 @@
...
+
+        executorService.shutdown();
+        executorService.awaitTermination(100, MILLISECONDS);
+
+        for (int i = 0; i < SHUTDOWN_ASYNC_TASKS_WAIT_REPORT_TIMES && !executorService.isTerminated(); i++) {
+            LOGGER.info("Waiting for asynchronous tasks to complete ...");
+            executorService.awaitTermination(SHUTDOWN_ASYNC_TASKS_WAIT_TIMEOUT.dividedBy(SHUTDOWN_ASYNC_TASKS_WAIT_REPORT_TIMES).toMillis(), TimeUnit.MILLISECONDS);
+        }
+        if (!executorService.isTerminated()) {
+            LOGGER.error("Some tasks did not finish, leaving them running");
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java]: will it make driver to finish with non zero status?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/benchmark/BenchmarkStatusReporter.java [hunk 9]
```diff
@@ -36,7 +38,10 @@
     public void sortExecutionListeners()
     {
         // HACK: listeners have to be sorted to provide tests determinism
```
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/benchmark/BenchmarkStatusReporter.java]: can this comment be removed now?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java (hunk 3 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: Letting measurement  provider return data after delay is the cornerstone of this change. If I don't "future-ize" this, I would need to couple the delay-related-logic in the calling code.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java (hunk 2 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: Done

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/measurements/ThroughputMeasurementProvider.java (hunk 5 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/measurements/ThroughputMeasurementProvider.java]: This is "Allow PostExecutionMeasurementProviders to be async" commit -- it does not introduce any asynchrony, it just makes API async-ready (by future-izing them). Asynchrony comes with "Query Graphite after configurable delay" commit and only for Graphite metrics loader (others don't need it).

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java (hunk 6 above)
Comment (findepi) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: Strange indeed. I didn't notice that. Nor did I introduce that. In fact `maxAttempts = 1` is quite popular in this class.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java (hunk 8 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java]: Nope. I will change this into an exc.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/benchmark/BenchmarkStatusReporter.java (hunk 9 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/benchmark/BenchmarkStatusReporter.java]: This still explains why there's sorting over `toString()`.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java (hunk 7 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java]: Only if there are jobs running. Since Graphite will be queried with 90s delay and since the measurement loading may (in an edge case) take longer that benchmarking itself, this times might accumulate a bit.. That's why there is so considerable a timeout. But we still exit as soon as the last is done.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/BenchmarkExecutionDriver.java [hunk 10]
```diff
@@ -94,32 +94,38 @@ public BenchmarkExecutionResult execute(Benchmark benchmark, int benchmarkOrdina
...
                     .build();
+        }
 
-            executionSynchronizer.awaitAfterBenchmarkExecutionAndBeforeResultReport(benchmark);
+        BenchmarkExecutionResult executionResult = resultBuilder
+                .withExecutions(executions)
+                .build();
 
-            statusReporter.reportBenchmarkFinished(executionResult);
+        executionSynchronizer.awaitAfterBenchmarkExecutionAndBeforeResultReport(benchmark);
```
Comment (sopel39) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/BenchmarkExecutionDriver.java]: was it supposed to throw exception too?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java [hunk 11]
```diff
@@ -69,6 +107,40 @@ public void awaitAfterBenchmarkExecutionAndBeforeResultReport(Benchmark benchmar
         }
     }
 
+    /**
+     * Executes {@code callable} when time comes. The {@code callable} gets executed immediately, without
+     * offloading to a backghround thread, if execution time requested has already passed.
+     */
+    public <T> CompletableFuture<T> execute(Instant when, Callable<T> callable)
+    {
+        if (!Instant.now().isBefore(when)) {
```
Comment (sopel39) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java]: `if (when.isBefore(Instant().now()))` would be easier to read

File: benchto-driver/src/test/resources/application.yaml [hunk 12]
```diff
@@ -23,6 +23,7 @@ presto:
 graphite:
   url: http://graphite:18088
   resolution.seconds: 1
+  metrics-delay.seconds: 0
```
Comment (sopel39) [inline benchto-driver/src/test/resources/application.yaml]: maybe use larger default than 0 since we know it is a default problem

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java [hunk 13]
```diff
@@ -47,6 +48,8 @@
 public class BenchmarkServiceExecutionListener
```
Comment (sopel39) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java]: maybe add base class `AsnynchroniousBenchmarkExecutionListener` so that async listeners don't have to implement large closures (which are not nicest to read)?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/GraphiteEventExecutionListener.java [hunk 14]
```diff
@@ -37,9 +38,18 @@
     private TaskExecutor taskExecutor;
 
     @Autowired
+    private ExecutionSynchronizer executionSynchronizer;
+
+    @Autowired
     private GraphiteClient graphiteClient;
 
     @Override
+    public int getOrder()
```
Comment (sopel39) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/GraphiteEventExecutionListener.java]: why order is required now since listeners are not async and https://github.com/prestodb/benchto/pull/25/commits/287c36cc29f1d994db187a218836950ec7d0b0e2#diff-5dce60daacbd65fc59e4ebfc7394dc57R41 is still valid?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java (hunk 1 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java]: > f that's the case then checking for null might be misleading since ...

Of course it IS misleading, hence the comment.

Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java]: > Maybe there a way to obtain timestamp (though additional REST query) of latest data point for a given metrics and do validation then.

It's certainly doable, but iff we asked Graphite about single metric, no aggregation. But we don't do that. Calling side currently knows nothing about aggregates and it make it quite much more complex if it did.

Unfortunately Graphite doesn't seem to offer (I searched for this) an option to return null for an aggregate if any ingredient is null.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java [hunk 15]
```diff
@@ -78,14 +78,19 @@ public void initQueryMetrics()
...
         }
 
-        long cutOffThresholdSeconds = executionSynchronizer.cutOffThresholdSecondsForMeasurementReporting();
+        /*
+         * Graphite can be queried with seconds resolution. It's `from` is exclusive (sic!, at least currently) but `until` is inclusive.
+         * Subtracting graphite resolution from `until` we effectively ask for the buckets that are fully covered by the `measurable`.
+         * This ignores first and last bucket (both partially covered), but gives most interesting statistics.
+         */
+        long fromEpochSecond = measurable.getUtcStart().toEpochSecond();
+        long toEpochSecond = measurable.getUtcEnd()
```
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: If it ended at `4.56`, we would truncate it to `4`, then subtract resolution and get `3`, so we will ask for all "buckets" until (inclusive) `3`. But "bucket" `3` covers range `[3, 4)`, so it will be (a) wholly covered by execution and (b) last one such.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java [hunk 16]
```diff
@@ -75,11 +78,19 @@ public void benchmarkStarted(Benchmark benchmark)
     @Override
     public void benchmarkFinished(BenchmarkExecutionResult benchmarkExecutionResult)
     {
-        FinishRequestBuilder requestBuilder = new FinishRequestBuilder()
-                .withStatus(benchmarkExecutionResult.isSuccessful() ? ENDED : FAILED)
-                .addMeasurements(getMeasurements(benchmarkExecutionResult));
-
-        benchmarkServiceClient.finishBenchmark(benchmarkExecutionResult.getBenchmark().getUniqueName(), benchmarkExecutionResult.getBenchmark().getSequenceId(), requestBuilder.build());
+        getMeasurements(benchmarkExecutionResult)
+                .thenApply(measurements -> {
```
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java]: Sure, not needed. They're only here for readability.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java [hunk 17]
```diff
@@ -94,34 +105,47 @@ public void executionStarted(QueryExecution execution)
...
-            if (executionResult.getFailureCause() instanceof SQLException) {
-                requestBuilder.addAttribute("failureSQLErrorCode", "" + ((SQLException) executionResult.getFailureCause()).getErrorCode());
-            }
-        }
-
-        benchmarkServiceClient.finishExecution(executionResult.getBenchmark().getUniqueName(), executionResult.getBenchmark().getSequenceId(),
-                executionSequenceId(executionResult.getQueryExecution()), requestBuilder.build());
+        getMeasurements(executionResult)
+                .thenApply(measurements -> {
+                    FinishRequestBuilder requestBuilder = new FinishRequestBuilder()
```
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java]: Cool idea!

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java [hunk 18]
```diff
@@ -94,34 +105,47 @@ public void executionStarted(QueryExecution execution)
...
+                            request);
+                });
     }
 
-    private List<Measurement> getMeasurements(Measurable measurable)
+    private CompletableFuture<List<Measurement>> getMeasurements(Measurable measurable)
     {
-        ImmutableList.Builder<Measurement> measurementsList = ImmutableList.builder();
+        List<CompletableFuture<?>> providerFutures = new ArrayList<>();
+        List<Measurement> measurementsList = Collections.synchronizedList(new ArrayList<>());
```
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java]: Yup, but `CompletableFuture.allOf` returns future of  `Void` rather than `List<T>`.

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java [hunk 19]
```diff
@@ -90,20 +90,24 @@ public void finishBenchmarkRun(String uniqueName, String sequenceId, Status stat
         benchmarkRun.getAttributes().putAll(attributes);
         benchmarkRun.setEnded(fromInstantOrCurrentDateTime(endTime));
         benchmarkRun.setStatus(status);
+        aggregateBenchmarkExecutions(benchmarkRun);
+        LOG.debug("Finishing benchmark - {}", benchmarkRun);
+    }
+
+    private void aggregateBenchmarkExecutions(BenchmarkRun benchmarkRun)
```
Comment (findepi) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: i amended the existing one to cover in-order and out-of-order cases.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/BenchmarkExecutionDriver.java (hunk 10 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/BenchmarkExecutionDriver.java]: Even if it did, we should not report `failedBenchmarkResult` in such a case, and we should fail loudly instead.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java (hunk 11 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/execution/ExecutionSynchronizer.java]: It would be, but it's not equivalent. I'd need `when.isBeforeOrEqual(now)` but there isn't any `isBeforeOrEqual` method)

File: benchto-driver/src/test/resources/application.yaml (hunk 12 above)
Comment (findepi) [inline benchto-driver/src/test/resources/application.yaml]: This is must here to have tests single-threaded. The REST mocking don't work otherwise.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java (hunk 13 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/BenchmarkServiceExecutionListener.java]: Admittedly, but... in fact none of the listeners could benefit it without overriding the base listener methods (not even `BenchmarkServiceExecutionListener`), so it's not actually a gain here.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/GraphiteEventExecutionListener.java (hunk 14 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/listeners/GraphiteEventExecutionListener.java]: Orders helps the logging listener be the first.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java (hunk 1 above)
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java]: I think it is better to do not have a metric than metric which is misleading. So once again, if it is known that there is value missing I would fail here (and retry later for couple of times?)

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java (hunk 3 above)
Comment (kokosing) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: Ok, but as I understand this code, it is serial anyway. Once the caller obtain the `Future` it will be already completed. Am I missing something? So this is why I see no benefit of using it here.

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java (hunk 6 above)
Comment (kokosing) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: Can you do a little investigation? To check why it is set to 1. Because I think it would be easier to remove this annotation at all. Maybe I don't know how this `@Retryable` works.

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java [hunk 20]
```diff
@@ -82,12 +83,12 @@ public String startBenchmarkRun(String uniqueName, String name, String sequenceI
 
     @Retryable(value = {TransientDataAccessException.class, DataIntegrityViolationException.class}, maxAttempts = 1)
     @Transactional
-    public void finishBenchmarkRun(String uniqueName, String sequenceId, Status status, List<Measurement> measurements, Map<String, String> attributes)
+    public void finishBenchmarkRun(String uniqueName, String sequenceId, Status status, Optional<Instant> endTime, List<Measurement> measurements, Map<String, String> attributes)
```
Comment (kokosing) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: if so, can parameter be deprecated?

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java (hunk 1 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteClient.java]: Okay, let the failure be with some retry.

File: benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java (hunk 3 above)
Comment (findepi) [inline benchto-driver/src/main/java/com/teradata/benchto/driver/graphite/GraphiteMetricsLoader.java]: > Ok, but as I understand this code, it is serial anyway.

The `Query Graphite after configurable delay` commit makes it non-serial.

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java (hunk 6 above)
Comment (findepi) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: It is so since ever (commit c266672689e27fdb80baf6345b1e3bcf5d6c7524) and the cmt msg does not contain a clue. This is orthogonal to the change under review, but if you wish, I can remove the `maxAttempts` attributes (default `3` will be used).

File: benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java (hunk 20 above)
Comment (findepi) [inline benchto-service/src/main/java/com/teradata/benchto/service/BenchmarkService.java]: "remove it" was about `Optional` wrapper, not about the parameter. The parameter is in no way deprecated (it's just introduced and is there to stay).
